/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subtitledelay;

import javax.swing.SpinnerNumberModel;
import java.io.FileNotFoundException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SpinnerModel;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.util.ArrayList;
import java.io.IOException;
import java.io.FileReader;
import java.io.File;


/**
 *
 * @author Daniel Munkacsi
 */
public class Main extends javax.swing.JFrame {

    private ArrayList<String> moddedtimes;
    private ArrayList<String> times;
    private ArrayList<String> file;
    private SpinnerModel smodel;
    private int delay;

    /**
     * Creates new form GUI
     */
    public Main() {
        super("Subtitle Delay");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeBtnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileArea = new javax.swing.JTextArea();
        setDelayBtn = new javax.swing.JButton();
        folderIcon = new javax.swing.JLabel();
        fileNameField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        timesArea = new javax.swing.JTextArea();
        delayField = new javax.swing.JTextField();
        applyBtn = new javax.swing.JButton();
        smodel = new SpinnerNumberModel(0.000,0.000,36000.000,0.001);
        delaySpinner = new javax.swing.JSpinner(smodel);
        secsBtn = new javax.swing.JRadioButton();
        milisecsBtn = new javax.swing.JRadioButton();
        decisecsBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutIcon = new javax.swing.JLabel();
        oldsubsLabel = new javax.swing.JLabel();
        newsubsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fileArea.setEditable(false);
        fileArea.setColumns(20);
        fileArea.setRows(5);
        jScrollPane1.setViewportView(fileArea);

        setDelayBtn.setText("Set delay");
        setDelayBtn.setEnabled(false);
        setDelayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDelayBtnActionPerformed(evt);
            }
        });

        folderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subtitledelay/folder_icon_small.png"))); // NOI18N
        folderIcon.setToolTipText("Open subtitle file");

        fileNameField.setEditable(false);
        fileNameField.setEnabled(false);

        saveBtn.setText("Save subs");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        timesArea.setEditable(false);
        timesArea.setColumns(10);
        timesArea.setRows(5);
        timesArea.setTabSize(5);
        timesArea.setAutoscrolls(false);
        jScrollPane2.setViewportView(timesArea);

        delayField.setEditable(false);
        delayField.setText("delay in seconds");
        delayField.setEnabled(false);

        applyBtn.setText("Apply delay");
        applyBtn.setEnabled(false);
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        delaySpinner.setEnabled(false);

        secsBtn.setText("seconds");
        secsBtn.setEnabled(false);
        timeBtnGroup.add(secsBtn);
        secsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secsBtnActionPerformed(evt);
            }
        });

        milisecsBtn.setText("milliseconds");
        milisecsBtn.setEnabled(false);
        timeBtnGroup.add(milisecsBtn);
        milisecsBtn.setSelected(true);
        milisecsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milisecsBtnActionPerformed(evt);
            }
        });

        decisecsBtn.setText("deciseconds");
        decisecsBtn.setEnabled(false);
        timeBtnGroup.add(decisecsBtn);
        decisecsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisecsBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("seconds");

        jLabel2.setText("Delay:");

        aboutIcon.setText("<html><b>?</b></html>");
        aboutIcon.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                displayAboutInfo();
            }
        });

        oldsubsLabel.setText("Original:");

        newsubsLabel.setText("New:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(folderIcon)
                        .addGap(18, 18, 18)
                        .addComponent(fileNameField)
                        .addGap(18, 18, 18)
                        .addComponent(aboutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(secsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(decisecsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milisecsBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(applyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setDelayBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delayField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldsubsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsubsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldsubsLabel)
                    .addComponent(newsubsLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secsBtn)
                            .addComponent(decisecsBtn)
                            .addComponent(milisecsBtn))
                        .addGap(18, 18, 18)
                        .addComponent(setDelayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delayField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(applyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folderIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aboutIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        folderIcon.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                openFileChooser();
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Read the user's input and create a new delay object.
     * @param evt the event triggered by button click, not used
     */
    private void setDelayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDelayBtnActionPerformed
        double dly = (double) smodel.getValue();
        String stringdelay = String.format("%.3f",dly);
        String[] dlyprts = stringdelay.split("\\.");
        int seconds = Integer.parseInt(dlyprts[0]);
        int milliseconds = Integer.parseInt(dlyprts[1]);
        if(seconds == 0 && milliseconds != 0){
            delay = milliseconds;
        }else if(seconds > 0 && milliseconds == 0){
            delay = seconds*1000;
        }else if(seconds > 0 && milliseconds != 0){
            delay = (seconds*1000) + milliseconds;
        }
        delayField.setText(stringdelay + " seconds");
        
        moddedtimes = new ArrayList<>();
        SubtitleDelay sd = new SubtitleDelay(delay,times,moddedtimes);
        sd.delaySubs();
        applyBtn.setEnabled(true);
        delayField.setEnabled(true);
        delayField.setCaretPosition(0);
    }//GEN-LAST:event_setDelayBtnActionPerformed
    
    /**
     * Apply the desired changes to the subtitles.
     * @param evt (not used)
     */
    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        ReplaceSubs replace = new ReplaceSubs(times,moddedtimes,file,timesArea); // pass file to listwriter when savebtn is pressed, for applybtn, process and display the list only
        replace.replaceSubs();
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_applyBtnActionPerformed
    
    /**
     * Save the delayed subtitles to file.
     * @param evt the event triggered by button click, not used
     */
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String filename = JOptionPane.showInputDialog("Please enter a name for the new subtitle file (don't include file type)");
        if(filename == null){return;}else if(filename.equals("")){JOptionPane.showMessageDialog(null, "Please enter a file name for the new subtitle file!", "Filename not given!", JOptionPane.ERROR_MESSAGE); return;}
        ListWriter lw = new ListWriter(filename + ".srt");
        lw.writeList(file, false); // true is append, false is normal write
    }//GEN-LAST:event_saveBtnActionPerformed

    private void secsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secsBtnActionPerformed
        SpinnerNumberModel nwmodel = (SpinnerNumberModel) smodel;
        nwmodel.setStepSize(1.000);
    }//GEN-LAST:event_secsBtnActionPerformed

    private void decisecsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisecsBtnActionPerformed
        SpinnerNumberModel nwmodel = (SpinnerNumberModel) smodel;
        nwmodel.setStepSize(0.100);
    }//GEN-LAST:event_decisecsBtnActionPerformed

    private void milisecsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milisecsBtnActionPerformed
        SpinnerNumberModel nwmodel = (SpinnerNumberModel) smodel;
        nwmodel.setStepSize(0.001);
    }//GEN-LAST:event_milisecsBtnActionPerformed
    
    /**
     * Display information about program.
     */
    private void displayAboutInfo(){
        String about = "Guide: " + "\n" 
                + "Open a subtitle file (type .srt or .txt) by clicking on the yellow folder icon. \n" 
                + "Set the delay using the incrementing box at the top. You can also manually type it in. \n"
                + "Press the \"Set delay \" button, then the \"Apply delay\" button. \n"
                + "If you're satisfied with the output, save. \n" 
                + "If you would like to edit the delay, do so but press the \"Set delay\" button once done changing it, then press \"Apply delay\" again"
                + "\n\n\n\n"
                + "Designed and created by Daniel Munkacsi.";
        JOptionPane.showMessageDialog(null, about, "About", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * Open a file chooser window.
     */
    private void openFileChooser(){
        file = new ArrayList<>();
        times = new ArrayList<>();
        
        JFileChooserSelectionOption fc = new JFileChooserSelectionOption();
        String chosenpath = fc.getPath();
        if(chosenpath == null) return;
        File f = new File(chosenpath);
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(f));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        fileNameField.setText(f.getName());
        
        
        String line = null;
        try {
            while((line = br.readLine()) != null){
                file.add(line);
                if(line.contains(" --> ")){ // this was .startsWith("0") , but what if the screenplay contains 0's in conversation? Or if the movie is longer than 10 hours?
                    times.add(line);
                }
            }
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayContent(f);
        secsBtn.setEnabled(true);
        decisecsBtn.setEnabled(true);
        milisecsBtn.setEnabled(true);
        setDelayBtn.setEnabled(true);
        delaySpinner.setEnabled(true);
        fileNameField.setEnabled(true);
    }
    
    /**
     * Display contents of a file.
     * @param f the file which should be read
     */
    private void displayContent(File f){
        fileArea.setText(f.getName() + " content:" + "\n");
        for(String s: file){
            fileArea.append(s + "\n");
        }
        timesArea.setText("Time stamps: " + "\n");
        for(String s: times){
            timesArea.append(s + "\n");
        }
        fileNameField.setCaretPosition(0);
        fileArea.setCaretPosition(0);
        timesArea.setCaretPosition(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutIcon;
    private javax.swing.JButton applyBtn;
    private javax.swing.JRadioButton decisecsBtn;
    private javax.swing.JTextField delayField;
    private javax.swing.JSpinner delaySpinner;
    private javax.swing.JTextArea fileArea;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JLabel folderIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton milisecsBtn;
    private javax.swing.JLabel newsubsLabel;
    private javax.swing.JLabel oldsubsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JRadioButton secsBtn;
    private javax.swing.JButton setDelayBtn;
    private javax.swing.ButtonGroup timeBtnGroup;
    private javax.swing.JTextArea timesArea;
    // End of variables declaration//GEN-END:variables
}